import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const redHatText = localFont({
  src: [
    {
      path: "./assets/fonts/RedHatText-VariableFont_wght.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/RedHatText-Italic-VariableFont_wght.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-red-hat-text",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Product List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${redHatText.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
